title: Medium Rare Books
email: brandstudio@intercom.io
description: >- # this means to ignore newlines until "baseurl:"
  Medium, rare books
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wooden-curlew.cloudvent.net/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: intercombrandstudio
instagram_username:  intercombrandstudio

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives

include: ['books']
paginate_path: "/books/page:num/"

sass:
sass_dir: css

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - index_files: true
    data: 'books'
    template: 'book'
    name: 'title'
    dir: 'books'
    filter: 'cataloged'
